# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on: [pull_request_target]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

  label-by-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      issues: write

    env:
      GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    steps:
      - name: Aplicar label feature
        if: startsWith(github.event.pull_request.title, 'feature:')
        run: gh pr edit ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --add-label "feature"

      - name: Aplicar label fix
        if: startsWith(github.event.pull_request.title, 'fix:')
        run: gh pr edit ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --add-label "fix"

      - name: Aplicar label chore
        if: startsWith(github.event.pull_request.title, 'documentation:')
        run: gh pr edit ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --add-label "documentation"